# Generated by Django 5.1 on 2024-08-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("subtitle", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="about_images/")),
                ("button_text", models.CharField(max_length=50)),
                ("button_link", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=300)),
                ("background_image", models.ImageField(upload_to="static/images/")),
                ("button_text", models.CharField(max_length=50)),
                ("button_link", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("price_description", models.CharField(max_length=15)),
                ("features", models.TextField()),
                ("button_text", models.CharField(max_length=50)),
                ("button_link", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("short_description", models.CharField(max_length=50)),
                ("long_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="PricingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("plans", models.ManyToManyField(to="home.pricingplan")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicesSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("subtitle", models.CharField(max_length=100)),
                ("services", models.ManyToManyField(to="home.servicecard")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
