# Generated by Django 5.1 on 2024-08-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.pricingplan",
                    ),
                ),
                (
                    "pricing_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.pricingsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
