# Generated by Django 5.1 on 2024-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_pricingorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsection",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/images/"),
        ),
    ]
