# Generated by Django 5.1 on 2024-09-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="total_num_assets",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="total_num_transactions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="total_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
