# Generated by Django 5.1 on 2024-08-25 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["-purchased_at"]},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
