# Generated by Django 5.1 on 2024-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolio_total_num_assets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="average_price",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="asset",
            name="total_quantity",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="asset",
            name="total_value",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
