# Generated by Django 5.1 on 2024-08-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_asset_options_alter_portfolio_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={"ordering": ["name"]},
        ),
    ]
