# Generated by Django 5.1 on 2024-09-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_asset_average_price_asset_total_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="price",
        ),
    ]
