# Generated by Django 5.1 on 2024-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_asset_options_alter_portfolio_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
