# Generated by Django 5.1 on 2024-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_portfolio_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(max_length=14),
        ),
    ]
